### ISSUE TITLE
In the Test details page, 'Output' Tab are empty although there do have some value in origin XML file

### ISSUE THREAD

**Issue by woshizhuyumi** [GHPReporter/Ghpr.Console#38] opened 2019-07-08 04:42 UTC
**Describe the bug**
I use the latest version of NUnit console runner to execute some test cases from a testcase.dll, and get an XML result in Nunit3 XML format.

After I use GHPReport console runner to convert it into HMTL result. in "Test details" page,  'Main' Tab looks good, but 'Output' Tab is empty.

I go back and check in the original XML result file, there do have some out logs, it just not showing up in the converted HTML file.

**To Reproduce**
1. Execute testcases.dll with latest Nunit3 console runner, and get an XML format result file.

2. Use GHPReporter_console to convert XML file into HTML files. using code `$originalTestResultFile = "C:\TestResults\NunitTestResult.xml"
C:\GHPReporter\GHPReporter_console\Ghpr.Console.exe $originalTestResultFile` 
in powershell. 
This image is what's in my GHPReporter_console folder: 
![image](https://user-images.githubusercontent.com/9000985/60783194-c515fa00-a19d-11e9-8e1f-ee78aada3d9f.png)

3. Then we have a folder of HTML result like this: 
![image](https://user-images.githubusercontent.com/9000985/60783241-e70f7c80-a19d-11e9-8158-1f2e23e2867a.png)

4. We open the HTML result page and go to any Test details page. We can see that 'Main' Tab looks good, but 'Output' and 'Extra output' Tabs are empty. please see 2 images below:
![image](https://user-images.githubusercontent.com/9000985/60783314-2938be00-a19e-11e9-9fc0-102e22c3d315.png)
![image](https://user-images.githubusercontent.com/9000985/60783321-33f35300-a19e-11e9-8879-95ce7ce6ee66.png)

5. I go back and check the XML file, I do see expect 'output' part has value like:
![image](https://user-images.githubusercontent.com/9000985/60783375-761c9480-a19e-11e9-87d7-2d1295477826.png)

**Expected behavior**
In HTML files, we expect the 'Output' tab to have the value that exists in XML file

**Screenshots**
Please see screenshots above

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser chrome
 - Version 75

**Attached XML file and HTML files**
Attached the original XML file and the result HTMLs I generated with console runner.
[XML+HTMLs.zip](https://github.com/GHPReporter/Ghpr.Console/files/3366690/XML%2BHTMLs.zip)

**Comment by davesliu** [comment] 2019-07-08 05:24
Maybe caused by the browser setting as shown in 

https://github.com/GHPReporter/Ghpr.Core


Firefox
Go to about:config
Find security.fileuri.strict_origin_policy parameter
Set it to false

Chrome
Close your Chrome
Launch it with --allow-file-access-from-files option:
eg C:\PATH TO\chrome.exe --allow-file-access-from-files

**Comment by woshizhuyumi** [comment] 2019-07-08 05:28
Thanks for the info @davesliu , but I already launch Chrome as you mentioned.
If I don't launch Chrome like that, the 'Main' Tab would be empty as well(I tried that.)
Now that the 'Main' Tab loads fine, we won't have the concerns as you suggested.

**Comment by elv1s42** [comment] 2019-07-08 08:33
Hi @woshizhuyumi !
This is bug, I'll investigate it and try to release the fix ASAP.

Thank you!

**Comment by woshizhuyumi** [comment] 2019-07-08 08:38
Thank you @elv1s42 , you are responding so quick!

**Comment by elv1s42** [comment] 2019-07-08 08:52
@woshizhuyumi , can you please confirm what NuGet package versions you are using?

**Comment by woshizhuyumi** [comment] 2019-07-08 08:58
Hi, @elv1s42  , I believe the Ghpr.Nunit I'm using is 0.9.9.0, and Ghpr.core is 0.9.9.1. please see 
![image](https://user-images.githubusercontent.com/9000985/60797331-2dc39d80-a1c3-11e9-9e54-a71224ff0a02.png)

**Comment by elv1s42** [comment] 2019-07-08 11:25
Hi @woshizhuyumi !

The bug was in the `Ghpr.LocalFileSystem' package, I've published the new version (0.9.9.2) which should contain the fix.

Can you please confirm the issue is no longer affecting you once you generate the report using updated packages?

Thank you

**Comment by woshizhuyumi** [comment] 2019-07-08 21:28
Hi @elv1s42 , I pulled the latest package of `Ghpr.LocalFileSystem` and it solves the problem, the issue is gone.
Thanks again for the quick response!

**Comment by elv1s42** [comment] 2019-07-09 09:23
Thank you @woshizhuyumi , I'm closing the issue then.

**Closed by elv1s42** 2019-07-09 09:23 UTC
Labels: bug, ghpr-core
